### PR TITLE
Fix 1-tuple regression.

### LINKED ISSUE #401: 1-tuple (el,) is converted to (el)
https://gist.github.com/tikue/c1857cbd7dc285c4bbd3

I believe 7b40bfa8d59b24699b29765fb9c5af0e4b82247f introduced the regression.

### PR DESCRIPTION
**Pull request by tikue**
Adds a test to prevent future regressions.

I hope it's ok that I enabled the slice patterns feature.

Fixes #401

### CODE REVIEW

**Comment by sinhpham** [comment]
Oh I didn't know that (x) is different than (x,), TIL.

File: src/types.rs [hunk 1]
```diff
@@ -483,22 +483,16 @@ impl Rewrite for ast::Ty {
...
-                                                                  // First item.
-                                                                  Some(x)
-                                                              } else {
-                                                                  Some(sum + ", " + &x)
-                                                              }
-                                                          }
-                                                          _ => None,
-                                                      }
-                                                  }));
+                let inner = if let [ref item] = &**tup_ret {
```
Comment (sinhpham) [inline src/types.rs]: Why not just if tup_ret.len() == 1?

File: src/types.rs [hunk 2]
```diff
@@ -483,22 +483,16 @@ impl Rewrite for ast::Ty {
...
+                    try_opt!(item.rewrite(context, width, offset).map(|rewrite| rewrite + ","))
+                } else {
+                    let rewrites: Option<Vec<_>>;
+                    rewrites = tup_ret.iter()
```
Comment (sinhpham) [inline src/types.rs]: The map(...).collect() will return an vector of optional string, not an optional vector of string. You're forcing it to ```Option<Vec<String>>``` by declaring the type earlier, so the next try_opt! will not do anything. This code will omit all items failed to format I believe.

The original code has a fold(...) part to detect if there is any None inside the vector, and returns None for the inner string if that's the case.

File: src/types.rs (hunk 1 above)
Comment (tikue) [inline src/types.rs]: Just a stylistic choice -- I'd have index into the vec after checking the length anyway, so I figured I'd do it all in one step. I don't feel strongly though.

File: src/types.rs (hunk 2 above)
Comment (tikue) [inline src/types.rs]: I believe the way `FromIterator` is implemented for `Option` preserves the intended semantics, actually -- http://is.gd/vDarSx. I'm not sure what you mean by forcing it to `Option<Vec<String>>` -- as far as I know a `Vec` can't just be coerced to an `Option`. The code returns Some(Vec<String>) if all the elements can be successfully re-written, and None otherwise. Then, try_opt!(rewrites).join(", ") either returns None or the rewritten elements with commas in between.

I was hoping that by shortening the code I'd make the code a bit clearer...

Comment (sinhpham) [inline src/types.rs]: Oh I didn't know that FromIterator already returns None in case 1 or more elements is None, you're right, discard what I said earlier.

On an unrelated note, how did you find that information? I don't seem to find it in the docs.

**Comment by marcusklaas** [comment]
Thanks!

File: src/types.rs (hunk 2 above)
Comment (tikue) [inline src/types.rs]: Honestly, I probably saw someone do it on reddit or IRC at some point...

...but it is indeed listed under implementors here -- https://doc.rust-lang.org/nightly/std/iter/trait.FromIterator.html. Note that it's not just `Option<Vec<T>>` but any `Option<A>` where `A` implements `FromIterator<T>`

Comment (sinhpham) [inline src/types.rs]: Oh I see, thanks @tikue
