### PR TITLE
Fix #201

### LINKED ISSUE #201: Unexpected coment added with struct syntax
Given the program:

```rust
fn main() {
    let state = get_state();
    let loop_body_state = ExecutionState { instr_ptr: 0, .. state.clone() };
}
```

Rustfmt generates the program:

```rust

fn main() {
    let state = get_state();
    let loop_body_state = ExecutionState { instr_ptr: 0 /* . */, ..state.clone() };
}
```

I don't think that comment should be there.

### PR DESCRIPTION
**Pull request by sinhpham**

### CODE REVIEW

File: src/expr.rs [hunk 1]
```diff
@@ -959,8 +959,14 @@ fn rewrite_struct_lit<'a>(context: &RewriteContext,
                              |item| {
                                  match *item {
                                      StructLitField::Regular(ref field) => field.span.lo,
-                                     // 2 = ..
-                                     StructLitField::Base(ref expr) => expr.span.lo - BytePos(2),
+                                     StructLitField::Base(ref expr) => {
+                                         let last_field_hi =
+                                             fields.last().map_or(span.lo, |field| field.span.hi);
+                                         let snippet =
+                                             context.codemap.span_to_snippet(mk_sp(last_field_hi, expr.span.lo)).unwrap();
```
Comment (marcusklaas) [inline src/expr.rs]: This was only just added yesterday, but could you use the `Context::snippet` helper here? Also, this seems to exceed the 100 column limit.

**Comment by cassiersg** [comment]
Thanks !
